apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-ssh-private
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'  # Kubernetes API server URL
    namespace: default
  project: default
  source:
    repoURL: "git@github.com:ngocHung2000/argocd-with-tekton-cicd.git"  # URL to your Git repository
    targetRevision: master
    path: ./03-deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false