apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-repo-deployment
spec:
  description: Read and display README file.
  workspaces:
  - name: source
  params:
    - name: IMAGE_NAME_DEPLOYMENT
    - name: IMAGE_VERSION
    - name: PATH_DEPLOYMENT
  steps:
  - name: read
    image: alpine:latest
    workingDir: "$(workspaces.source.path)/$(params.PATH_DEPLOYMENT)"
    script: | 
      #!/usr/bin/env sh
      ls -lah
      cat deployment-nodes-app.yaml
      echo "============================================================="
      sed -i 's/$(params.IMAGE_NAME_DEPLOYMENT).*/$(params.IMAGE_NAME_DEPLOYMENT):$(params.IMAGE_VERSION)/g' deployment-nodes-app.yaml
      cat deployment-nodes-app.yaml
