apiVersion: v1
kind: Secret
metadata:
  name: argocd-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository  
stringData:
  type: git
  url: git@github.com:ngocHung2000/argocd-with-tekton-cicd.git
  sshPrivateKey: |
    PRIVATE_KEY_GIT_HUB

